---
version: "2.0"

services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.3.26-evmos-v11.0.2
    env:
      - MONIKER=SG-1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/evmos/chain.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=0 
      - SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/evmos/evmos_12820560.tar.lz4
      - SNAPSHOT_DATA_PATH=data
      - ADDRBOOK_URL=https://snapshots.polkachu.com/addrbook/evmos/addrbook.json
      - P2P_SEEDS=ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:13456
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    # params:
    #   storage:
    #     data:
    #       mount: /root/.evmosd

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        storage:
          - name: data
            size: 120Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 1000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
